# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import test_dummy.paths.u_linline_schema_propertiesu_l.get.responses.default.content.applicationu_ljson.schema.properties.prop1.schema


class schema(lapidary.runtime.ModelBase):
    
    prop1: test_dummy.paths.u_linline_schema_propertiesu_l.get.responses.default.content.applicationu_ljson.schema.properties.prop1.schema.prop1
    
    model_config = pydantic.ConfigDict(extra='forbid',)
