# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import types


class ApiResponse(lapidary.runtime.ModelBase):
    
    code: typing.Union[
            int,
            None,
        ] = None
    
    type: typing.Union[
            str,
            None,
        ] = None
    
    message: typing.Union[
            str,
            None,
        ] = None
