# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary
import pydantic
import typing_extensions as typing


class prop1(lapidary.ModelBase):
    
    prop2: str
    
    model_config = pydantic.ConfigDict(extra='forbid',)
