# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import types


class RequestMetadata(pydantic.BaseModel):
    
    param1_h: typing.Annotated[
            typing.Union[
            str,
            None,
        ],
            lapidary.runtime.Header('param1',),
        ] = None
    
    param4_c: typing.Annotated[
            typing.Union[
            list[str,],
            None,
        ],
            lapidary.runtime.Cookie(
        'param4',
        style=lapidary.runtime.Form,
    ),
        ] = None
