# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import datetime
import types


class Order(lapidary.runtime.ModelBase):
    
    id: typing.Union[
            int,
            None,
        ] = None
    
    petId: typing.Union[
            int,
            None,
        ] = None
    
    quantity: typing.Union[
            int,
            None,
        ] = None
    
    shipDate: typing.Union[
            datetime.datetime,
            None,
        ] = None
    
    status: typing.Union[
            str,
            None,
        ] = None
    
    complete: typing.Union[
            bool,
            None,
        ] = None
