# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations

import lapidary
import pydantic
import typing_extensions as typing
import datetime
import types


class Order(lapidary.ModelBase):
    
    id: int | None = None
    
    petId: int | None = None
    
    quantity: int | None = None
    
    shipDate: datetime.datetime | None = None
    
    status: str | None = None
    
    complete: bool | None = None
