# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations

import lapidary
import pydantic
import typing_extensions as typing
import datetime


class schema(lapidary.ModelBase):
    
    prop1: datetime.date
    
    model_config = pydantic.ConfigDict(extra='forbid',)
