# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: '3.12'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: ^src/lapidary/render/templates/render/includes/header.txt$|^tests/e2e/expected/
  - id: no-commit-to-branch
  - id: trailing-whitespace
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.3
  hooks:
  - id: ruff
    name: ruff-check
    pass_filenames: false
    args:
    - --fix
  - id: ruff-format
    pass_filenames: false
- repo: https://github.com/python-poetry/poetry
  rev: 1.8.3
  hooks:
  - id: poetry-check
  - id: poetry-lock
    args:
    - --no-update
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.2
  hooks:
  - id: mypy
    pass_filenames: false
    args:
    - --enable-incomplete-feature=NewGenericSyntax
