# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_language_version:
  python: '3.12'
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: ^src/lapidary/render/templates/render/includes/header.txt$|^tests/e2e/expected/
  - id: check-added-large-files
  - id: check-toml
  - id: debug-statements
    exclude: src/lapidary/render/templates
  - id: check-yaml
    exclude: src/lapidary/render/templates
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.10
  hooks:
  - id: ruff
    name: ruff check
    pass_filenames: false
  - id: ruff-format
    pass_filenames: false
