# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations

import lapidary
import pydantic
import typing_extensions as typing
import datetime
import types


class ResponseMetadata(pydantic.BaseModel):
    
    Xu_jRateu_jLimit: typing.Annotated[
            int | None,
            lapidary.Header(
        'X-Rate-Limit',
        style=lapidary.SimpleMultimap,
    ),
        ] = None
    
    Xu_jExpiresu_jAfter: typing.Annotated[
            datetime.datetime | None,
            lapidary.Header(
        'X-Expires-After',
        style=lapidary.SimpleMultimap,
    ),
        ] = None
