# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary
import pydantic
import typing_extensions as typing
import test_petstore.components.schemas.Category.schema
import test_petstore.components.schemas.Tag.schema
import types


class Pet(lapidary.ModelBase):
    
    id: int | None = None
    
    name: str
    
    category: test_petstore.components.schemas.Category.schema.Category | None = None
    
    photoUrls: list[str,]
    
    tags: list[test_petstore.components.schemas.Tag.schema.Tag,] | None = None
    
    status: str | None = None
