# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import types


class RequestMetadata(pydantic.BaseModel):
    
    api_key_h: typing.Annotated[
            typing.Union[
            str,
            None,
        ],
            lapidary.runtime.Header('api_key',),
        ] = None
