# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary
import pydantic
import typing_extensions as typing
import types


class ApiResponse(lapidary.ModelBase):
    
    code: int | None = None
    
    type: str | None = None
    
    message: str | None = None
