# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import test_dummy.components.schemas.schema1.properties.prop1.properties.prop2.schema


class prop1(lapidary.runtime.ModelBase):
    
    prop2: test_dummy.components.schemas.schema1.properties.prop1.properties.prop2.schema.prop2
    
    model_config = pydantic.ConfigDict(extra='forbid',)
