# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary
import pydantic
import typing_extensions as typing
import collections.abc
import httpx
import httpx_auth
import lapidary.auth


def oauth2_implicit_oauth(
    scope: collections.abc.Iterable[typing.Literal[
        'read',
        'write',
    ]] | None = None,
    **kwargs,
) -> httpx.Auth:
    if scope is not None:
        kwargs['scope'] = ' '.join(scope)

    return httpx_auth.OAuth2Implicit(
        authorization_url='https://example.com/authorization_url',
        **kwargs,
    )


def oauth2_password_oauth(
    username: str,
    password: str,
    scope: collections.abc.Iterable[typing.Literal[
        'read',
        'write',
    ]] | None = None,
    **kwargs,
) -> httpx.Auth:
    if scope is not None:
        kwargs['scope'] = ' '.join(scope)

    return httpx_auth.OAuth2ResourceOwnerPasswordCredentials(
        token_url='https://example.com/token_url',
        username=username,
        password=password,
        **kwargs,
    )


def oauth2_authorization_code_oauth(
    scope: collections.abc.Iterable[typing.Literal[
        'read',
        'write',
    ]] | None = None,
    **kwargs,
) -> httpx.Auth:
    if scope is not None:
        kwargs['scope'] = ' '.join(scope)

    return httpx_auth.OAuth2AuthorizationCode(
        authorization_url='https://example.com/authorization_url',
        token_url='https://example.com/token_url',
        **kwargs,
    )


def oauth2_client_credentials_oauth(
    client_id: str,
    client_secret: str,
    scope: collections.abc.Iterable[typing.Literal[
        'read',
        'write',
    ]] | None = None,
    **kwargs,
) -> httpx.Auth:
    if scope is not None:
        kwargs['scope'] = ' '.join(scope)

    return httpx_auth.OAuth2ClientCredentials(
        token_url='https://example.com/token_url',
        client_id=client_id,
        client_secret=client_secret,
        **kwargs,
    )


def api_key_apiu_jkey(api_key: str) -> httpx.Auth:
    return lapidary.auth.HeaderApiKey(
        api_key=api_key,
        header_name='x-api-key',
    )


def api_key_apiu_jkeyu_jcookie(api_key: str) -> httpx.Auth:
    return lapidary.auth.CookieApiKey(
        api_key=api_key,
        cookie_name='x-api-key',
    )


def api_key_apiu_jkeyu_jquery(api_key: str) -> httpx.Auth:
    return lapidary.auth.QueryApiKey(
        api_key=api_key,
        query_parameter_name='x-api-key',
    )


def http_basic_http_basic(
    user_name: str,
    password: str
) -> httpx.Auth:
    return httpx.BasicAuth(
        username=user_name,
        password=password,
    )


def http_digest_http_digest(
    user_name: str,
    password: str
) -> httpx.Auth:
    return httpx.DigestAuth(
        username=user_name,
        password=password,
    )
