# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations

__all__ = (
    'ApiClient',
)

import lapidary
import pydantic
import typing_extensions as typing
import test_petstore.components.schemas.ApiResponse.schema
import test_petstore.components.schemas.Order.schema
import test_petstore.components.schemas.Pet.schema
import test_petstore.components.schemas.User.schema
import test_petstore.paths.u_lpetu_lu_1zpetIdu_21.delete.parameters.meta
import test_petstore.paths.u_luseru_llogin.get.responses.u_o00.headers
import types


class ApiClient:
    lapidary_base_url = 'https://petstore3.swagger.io/v3'
    
    @lapidary.post('/pet',)
    async def addPet(
        self: typing.Self,
        body: typing.Annotated[
            test_petstore.components.schemas.Pet.schema.Pet,
            lapidary.Body({
                'application/json': test_petstore.components.schemas.Pet.schema.Pet,
            },),
        ],
    ) -> typing.Annotated[
            tuple[
            test_petstore.components.schemas.Pet.schema.Pet,
            None,
        ],
            lapidary.Responses({
                '200': lapidary.Response(
                    lapidary.Body({
                        'application/json': test_petstore.components.schemas.Pet.schema.Pet,
                    },),
                ),
                '405': lapidary.Response(
                    lapidary.Body({},),
                ),
            },),
        ]:
        pass
    
    @lapidary.put('/pet',)
    async def updatePet(
        self: typing.Self,
        body: typing.Annotated[
            test_petstore.components.schemas.Pet.schema.Pet,
            lapidary.Body({
                'application/json': test_petstore.components.schemas.Pet.schema.Pet,
            },),
        ],
    ) -> typing.Annotated[
            tuple[
            test_petstore.components.schemas.Pet.schema.Pet,
            None,
        ],
            lapidary.Responses({
                '200': lapidary.Response(
                    lapidary.Body({
                        'application/json': test_petstore.components.schemas.Pet.schema.Pet,
                    },),
                ),
                '400': lapidary.Response(
                    lapidary.Body({},),
                ),
                '404': lapidary.Response(
                    lapidary.Body({},),
                ),
                '405': lapidary.Response(
                    lapidary.Body({},),
                ),
            },),
        ]:
        pass
    
    @lapidary.get('/pet/findByStatus',)
    async def findPetsByStatus(
        self: typing.Self,
        *, status_q: typing.Annotated[
            str | None,
            lapidary.Query(
        'status',
        style=lapidary.FormExplode,
    ),
        ] = None,
    ) -> typing.Annotated[
            tuple[
            list[test_petstore.components.schemas.Pet.schema.Pet,],
            None,
        ],
            lapidary.Responses({
                '200': lapidary.Response(
                    lapidary.Body({
                        'application/json': list[test_petstore.components.schemas.Pet.schema.Pet,],
                    },),
                ),
                '400': lapidary.Response(
                    lapidary.Body({},),
                ),
            },),
        ]:
        pass
    
    @lapidary.get('/pet/findByTags',)
    async def findPetsByTags(
        self: typing.Self,
        *, tags_q: typing.Annotated[
            list[str,] | None,
            lapidary.Query(
        'tags',
        style=lapidary.FormExplode,
    ),
        ] = None,
    ) -> typing.Annotated[
            tuple[
            list[test_petstore.components.schemas.Pet.schema.Pet,],
            None,
        ],
            lapidary.Responses({
                '200': lapidary.Response(
                    lapidary.Body({
                        'application/json': list[test_petstore.components.schemas.Pet.schema.Pet,],
                    },),
                ),
                '400': lapidary.Response(
                    lapidary.Body({},),
                ),
            },),
        ]:
        pass
    
    @lapidary.get('/pet/{petId}',)
    async def getPetById(
        self: typing.Self,
        *, petId_p: typing.Annotated[
            int,
            lapidary.Path('petId',),
        ],
    ) -> typing.Annotated[
            tuple[
            test_petstore.components.schemas.Pet.schema.Pet,
            None,
        ],
            lapidary.Responses({
                '200': lapidary.Response(
                    lapidary.Body({
                        'application/json': test_petstore.components.schemas.Pet.schema.Pet,
                    },),
                ),
                '400': lapidary.Response(
                    lapidary.Body({},),
                ),
                '404': lapidary.Response(
                    lapidary.Body({},),
                ),
            },),
        ]:
        pass
    
    @lapidary.post('/pet/{petId}',)
    async def updatePetWithForm(
        self: typing.Self,
        *, petId_p: typing.Annotated[
            int,
            lapidary.Path('petId',),
        ],
        name_q: typing.Annotated[
            str | None,
            lapidary.Query('name',),
        ] = None,
        status_q: typing.Annotated[
            str | None,
            lapidary.Query('status',),
        ] = None,
    ) -> typing.Annotated[
            None,
            lapidary.Responses({
                '405': lapidary.Response(
                    lapidary.Body({},),
                ),
            },),
        ]:
        pass
    
    @lapidary.delete('/pet/{petId}',)
    async def deletePet(
        self: typing.Self,
        *, petId_p: typing.Annotated[
            int,
            lapidary.Path('petId',),
        ],
        meta: typing.Annotated[
            test_petstore.paths.u_lpetu_lu_1zpetIdu_21.delete.parameters.meta.RequestMetadata | None,
            lapidary.Metadata,
        ] = None,
    ) -> typing.Annotated[
            None,
            lapidary.Responses({
                '400': lapidary.Response(
                    lapidary.Body({},),
                ),
            },),
        ]:
        pass
    
    @lapidary.post('/pet/{petId}/uploadImage',)
    async def uploadFile(
        self: typing.Self,
        *, petId_p: typing.Annotated[
            int,
            lapidary.Path('petId',),
        ],
        additionalMetadata_q: typing.Annotated[
            str | None,
            lapidary.Query('additionalMetadata',),
        ] = None,
    ) -> typing.Annotated[
            tuple[
            test_petstore.components.schemas.ApiResponse.schema.ApiResponse,
            None,
        ],
            lapidary.Responses({
                '200': lapidary.Response(
                    lapidary.Body({
                        'application/json': test_petstore.components.schemas.ApiResponse.schema.ApiResponse,
                    },),
                ),
            },),
        ]:
        pass
    
    @lapidary.get('/store/inventory',)
    async def getInventory(
        self: typing.Self,
    ) -> typing.Annotated[
            tuple[
            dict[
                str,
                pydantic.JsonValue,
            ],
            None,
        ],
            lapidary.Responses({
                '200': lapidary.Response(
                    lapidary.Body({
                        'application/json': dict[
                            str,
                            pydantic.JsonValue,
                        ],
                    },),
                ),
            },),
        ]:
        pass
    
    @lapidary.post('/store/order',)
    async def placeOrder(
        self: typing.Self,
        body: typing.Annotated[
            test_petstore.components.schemas.Order.schema.Order,
            lapidary.Body({
                'application/json': test_petstore.components.schemas.Order.schema.Order,
            },),
        ],
    ) -> typing.Annotated[
            tuple[
            test_petstore.components.schemas.Order.schema.Order,
            None,
        ],
            lapidary.Responses({
                '200': lapidary.Response(
                    lapidary.Body({
                        'application/json': test_petstore.components.schemas.Order.schema.Order,
                    },),
                ),
                '405': lapidary.Response(
                    lapidary.Body({},),
                ),
            },),
        ]:
        pass
    
    @lapidary.get('/store/order/{orderId}',)
    async def getOrderById(
        self: typing.Self,
        *, orderId_p: typing.Annotated[
            int,
            lapidary.Path('orderId',),
        ],
    ) -> typing.Annotated[
            tuple[
            test_petstore.components.schemas.Order.schema.Order,
            None,
        ],
            lapidary.Responses({
                '200': lapidary.Response(
                    lapidary.Body({
                        'application/json': test_petstore.components.schemas.Order.schema.Order,
                    },),
                ),
                '400': lapidary.Response(
                    lapidary.Body({},),
                ),
                '404': lapidary.Response(
                    lapidary.Body({},),
                ),
            },),
        ]:
        pass
    
    @lapidary.delete('/store/order/{orderId}',)
    async def deleteOrder(
        self: typing.Self,
        *, orderId_p: typing.Annotated[
            int,
            lapidary.Path('orderId',),
        ],
    ) -> typing.Annotated[
            None,
            lapidary.Responses({
                '400': lapidary.Response(
                    lapidary.Body({},),
                ),
                '404': lapidary.Response(
                    lapidary.Body({},),
                ),
            },),
        ]:
        pass
    
    @lapidary.post('/user',)
    async def createUser(
        self: typing.Self,
        body: typing.Annotated[
            test_petstore.components.schemas.User.schema.User,
            lapidary.Body({
                'application/json': test_petstore.components.schemas.User.schema.User,
            },),
        ],
    ) -> typing.Annotated[
            tuple[
            test_petstore.components.schemas.User.schema.User,
            None,
        ],
            lapidary.Responses({
                'default': lapidary.Response(
                    lapidary.Body({
                        'application/json': test_petstore.components.schemas.User.schema.User,
                    },),
                ),
            },),
        ]:
        pass
    
    @lapidary.post('/user/createWithList',)
    async def createUsersWithListInput(
        self: typing.Self,
        body: typing.Annotated[
            list[test_petstore.components.schemas.User.schema.User,],
            lapidary.Body({
                'application/json': list[test_petstore.components.schemas.User.schema.User,],
            },),
        ],
    ) -> typing.Annotated[
            tuple[
                test_petstore.components.schemas.User.schema.User,
                None,
            ] | tuple[
                None,
                None,
            ],
            lapidary.Responses({
                '200': lapidary.Response(
                    lapidary.Body({
                        'application/json': test_petstore.components.schemas.User.schema.User,
                    },),
                ),
                'default': lapidary.Response(
                    lapidary.Body({},),
                ),
            },),
        ]:
        pass
    
    @lapidary.get('/user/login',)
    async def loginUser(
        self: typing.Self,
        *, username_q: typing.Annotated[
            str | None,
            lapidary.Query('username',),
        ] = None,
        password_q: typing.Annotated[
            str | None,
            lapidary.Query('password',),
        ] = None,
    ) -> typing.Annotated[
            tuple[
            str,
            test_petstore.paths.u_luseru_llogin.get.responses.u_o00.headers.ResponseMetadata,
        ],
            lapidary.Responses({
                '200': lapidary.Response(
                    lapidary.Body({
                        'application/json': str,
                    },),
                    test_petstore.paths.u_luseru_llogin.get.responses.u_o00.headers.ResponseMetadata,
                ),
                '400': lapidary.Response(
                    lapidary.Body({},),
                ),
            },),
        ]:
        pass
    
    @lapidary.get('/user/logout',)
    async def logoutUser(
        self: typing.Self,
    ) -> typing.Annotated[
            tuple[
            None,
            None,
        ],
            lapidary.Responses({
                'default': lapidary.Response(
                    lapidary.Body({},),
                ),
            },),
        ]:
        pass
    
    @lapidary.get('/user/{username}',)
    async def getUserByName(
        self: typing.Self,
        *, username_p: typing.Annotated[
            str,
            lapidary.Path('username',),
        ],
    ) -> typing.Annotated[
            tuple[
            test_petstore.components.schemas.User.schema.User,
            None,
        ],
            lapidary.Responses({
                '200': lapidary.Response(
                    lapidary.Body({
                        'application/json': test_petstore.components.schemas.User.schema.User,
                    },),
                ),
                '400': lapidary.Response(
                    lapidary.Body({},),
                ),
                '404': lapidary.Response(
                    lapidary.Body({},),
                ),
            },),
        ]:
        pass
    
    @lapidary.put('/user/{username}',)
    async def updateUser(
        self: typing.Self,
        body: typing.Annotated[
            test_petstore.components.schemas.User.schema.User,
            lapidary.Body({
                'application/json': test_petstore.components.schemas.User.schema.User,
            },),
        ],
        *, username_p: typing.Annotated[
            str,
            lapidary.Path('username',),
        ],
    ) -> typing.Annotated[
            tuple[
            None,
            None,
        ],
            lapidary.Responses({
                'default': lapidary.Response(
                    lapidary.Body({},),
                ),
            },),
        ]:
        pass
    
    @lapidary.delete('/user/{username}',)
    async def deleteUser(
        self: typing.Self,
        *, username_p: typing.Annotated[
            str,
            lapidary.Path('username',),
        ],
    ) -> typing.Annotated[
            None,
            lapidary.Responses({
                '400': lapidary.Response(
                    lapidary.Body({},),
                ),
                '404': lapidary.Response(
                    lapidary.Body({},),
                ),
            },),
        ]:
        pass
