# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations

__all__ = (
    'ApiClient',
)

import lapidary
import pydantic
import typing_extensions as typing
import annotated_types
import datetime
import test_dummy.components.requestBodies.dummy.content.applicationu_ljson.schema.schema
import test_dummy.components.schemas.all.schema
import test_dummy.components.schemas.schema1.schema
import test_dummy.paths.u_linline_schema_propertiesu_l.get.responses.default.content.applicationu_ljson.schema.schema
import test_dummy.paths.u_ltestu_l.get.parameters.meta
import test_dummy.paths.u_ltestu_l.get.parameters.u_n.schema.schema
import test_dummy.paths.u_ltestu_l.get.responses.default.headers
import types


class ApiClient:
    lapidary_base_url = '/'
    
    @lapidary.get('/test/',)
    async def test_op(
        self: typing.Self,
        *, param1_q: typing.Annotated[
            typing.Annotated[
                int,
                annotated_types.Le(20,),
            ] | test_dummy.components.schemas.all.schema.all | test_dummy.components.schemas.schema1.schema.schema1 | None,
            lapidary.Query('param1',),
        ],
        param2_q: typing.Annotated[
            test_dummy.paths.u_ltestu_l.get.parameters.u_n.schema.schema.schema | None,
            lapidary.Query('param2',),
        ] = None,
        param3_q: typing.Annotated[
            datetime.date | None,
            lapidary.Query('param3',),
        ] = None,
        meta: typing.Annotated[
            test_dummy.paths.u_ltestu_l.get.parameters.meta.RequestMetadata | None,
            lapidary.Metadata,
        ] = None,
    ) -> typing.Annotated[
            tuple[
                test_dummy.components.schemas.all.schema.all,
                test_dummy.paths.u_ltestu_l.get.responses.default.headers.ResponseMetadata,
            ] | tuple[
                test_dummy.components.schemas.all.schema.all,
                None,
            ],
            lapidary.Responses({
                'default': lapidary.Response(
                    lapidary.Body({
                        'application/json': test_dummy.components.schemas.all.schema.all,
                    },),
                    test_dummy.paths.u_ltestu_l.get.responses.default.headers.ResponseMetadata,
                ),
                '2XX': lapidary.Response(
                    lapidary.Body({
                        'application/json': test_dummy.components.schemas.all.schema.all,
                    },),
                ),
            },),
        ]:
        pass
    
    @lapidary.get('/inline_schema_properties/',)
    async def inline_schema_properties(
        self: typing.Self,
    ) -> typing.Annotated[
            tuple[
            test_dummy.paths.u_linline_schema_propertiesu_l.get.responses.default.content.applicationu_ljson.schema.schema.schema,
            None,
        ],
            lapidary.Responses({
                'default': lapidary.Response(
                    lapidary.Body({
                        'application/json': test_dummy.paths.u_linline_schema_propertiesu_l.get.responses.default.content.applicationu_ljson.schema.schema.schema,
                    },),
                ),
            },),
        ]:
        pass
    
    @lapidary.get('/custom-security',)
    async def customSecurity(
        self: typing.Self,
    ) -> typing.Annotated[
            tuple[
            list[test_dummy.components.schemas.all.schema.all,],
            None,
        ],
            lapidary.Responses({
                'default': lapidary.Response(
                    lapidary.Body({
                        'application/json': list[test_dummy.components.schemas.all.schema.all,],
                    },),
                ),
            },),
        ]:
        pass
    
    @lapidary.get('/insecure',)
    async def insecure(
        self: typing.Self,
        body: typing.Annotated[
            test_dummy.components.requestBodies.dummy.content.applicationu_ljson.schema.schema.schema,
            lapidary.Body({
                'application/json': test_dummy.components.requestBodies.dummy.content.applicationu_ljson.schema.schema.schema,
            },),
        ],
    ) -> typing.Annotated[
            tuple[
            test_dummy.components.schemas.all.schema.all,
            None,
        ],
            lapidary.Responses({
                'default': lapidary.Response(
                    lapidary.Body({
                        'application/json': test_dummy.components.schemas.all.schema.all,
                    },),
                ),
            },),
        ]:
        pass
