# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary
import pydantic
import typing_extensions as typing
import types


class ResponseMetadata(pydantic.BaseModel):
    
    xu_jcount: typing.Annotated[
            int | None,
            lapidary.Header(
        'x-count',
        style=lapidary.SimpleMultimap,
    ),
        ] = None
