# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import types


class ResponseMetadata(pydantic.BaseModel):
    
    xu_jcount: typing.Annotated[
            typing.Union[
            int,
            None,
        ],
            lapidary.runtime.Header(
        'x-count',
        style=lapidary.runtime.SimpleMultimap,
    ),
        ] = None
