# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary
import pydantic
import typing_extensions as typing
import types


class RequestMetadata(pydantic.BaseModel):
    
    param1_h: typing.Annotated[
            str | None,
            lapidary.Header('param1',),
        ] = None
    
    param4_c: typing.Annotated[
            list[str,] | None,
            lapidary.Cookie(
        'param4',
        style=lapidary.Form,
    ),
        ] = None
