# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary
import pydantic
import typing_extensions as typing
import collections.abc
import httpx
import httpx_auth
import lapidary.auth


def oauth2_implicit_petstore_auth(
    scope: typing.Union[
        collections.abc.Iterable[typing.Literal[
        'write:pets',
        'read:pets',
    ]],
        None
    ] = None,
    **kwargs,
) -> httpx.Auth:
    if scope is not None:
        kwargs['scope'] = ' '.join(scope)

    return httpx_auth.OAuth2Implicit(
        authorization_url='https://petstore.swagger.io/oauth/authorize',
        **kwargs,
    )


def api_key_api_key(api_key: str) -> httpx.Auth:
    return lapidary.auth.HeaderApiKey(
        api_key=api_key,
        header_name='api_key',
    )
