# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary
import pydantic
import typing_extensions as typing
import types


class Category(lapidary.ModelBase):
    
    id: int | None = None
    
    name: str | None = None
