# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary.runtime
import pydantic
import typing_extensions as typing
import types


class Category(lapidary.runtime.ModelBase):
    
    id: typing.Union[
            int,
            None,
        ] = None
    
    name: typing.Union[
            str,
            None,
        ] = None
