# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations

import lapidary
import pydantic
import typing_extensions as typing
import types


class RequestMetadata(pydantic.BaseModel):
    
    api_key_h: typing.Annotated[
            str | None,
            lapidary.Header('api_key',),
        ] = None
