# This file is automatically @generated by Lapidary and should not be changed by hand.

from __future__ import annotations
import lapidary
import pydantic
import typing_extensions as typing
import types


class User(lapidary.ModelBase):
    
    id: int | None = None
    
    username: str | None = None
    
    firstName: str | None = None
    
    lastName: str | None = None
    
    email: str | None = None
    
    password: str | None = None
    
    phone: str | None = None
    
    userStatus: int | None = None
