name: Publish Poetry Package to PyPI

on:
  push:
    tags:
    - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: pipx install poetry==2.3.2
    - name: Cache dependencies
      uses: actions/cache@v5
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}
    - name: Mint token
      id: mint
      uses: tschm/token-mint-action@v1.0.3
    - name: Publish the package
      run: poetry publish --build -u __token__ -p '${{ steps.mint.outputs.api-token }}'
